Server:
  port: "9001"

MySQL:
  host: 127.0.0.1
  port: 3306
  user: root
  pass: semaik1023
  dbName: watchalert
  timeout: 10s

Redis:
  host: 127.0.0.1
  port: 6379
  pass: ""

Jwt:
  # 失效时间
  expire: 40000