Server:
  port: "9001"
  # 定义相同的Group之间发送告警通知的时间间隔(s)
  groupInterval: 120

MySQL:
  host: 127.0.0.1
  port: 3306
  user: root
  pass: semaik1023
  dbName: watchalert
  timeout: 10s

Redis:
  host: 127.0.0.1
  port: 6379
  pass: ""

Jwt:
  # 失效时间
  expire: 18000