server:
  port: "9001"

feishu:
  # 应用ID
  appId: "cli_a4cdcxxxxxxd00d"
  # 应用密钥
  appSecret: "Q8rnC3eIZTcxxxxxxgECQuqM"
  # Token
  token: "t-g104beebK2PxxxxxxCUDGNFU"

AlertManager:
  url: "http://192.168.1.176:9093"
  # 静默时长(单位分钟)
  silenceTime: "120"

Prometheus:
  url: "http://192.168.1.176:9090"
  rulePath: "/Users/zuxuan/Documents/worksapce/prometheus/prom_data/rules"

Jaeger:
  url: "https://jg.test.com"

MySQL:
  host: 192.168.1.176
  port: 3306
  user: root
  pass: xxxxxx
  dbName: watchalert
  timeout: 10s
