server:
  port: "9001"

feishu:
  # 应用ID
  appId: "cli_a47d40b4c1b8500b"
  # 应用密钥
  appSecret: "6eRbSMvV2suwPveLOxsnvedIwSwhBT8U"
  # 群ID
  chatId: "oc_d3945d051a1b8b9df717c5674b62a27c"
  # Token
  token: "t-g10497bJKBHXGZ564SEW5RSDD36AGMZFQ5D5IIFU"

AlertManager:
  url: "http://172.17.84.238:9093"
  # 静默时长(单位分钟)
  silenceTime: "120"
